name: Validate item data

permissions:
  issues: write

on:
  push:
    paths:
      - "items/**/*.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pipenv

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install python dependencies
        working-directory: builder
        run: pipenv sync

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install ajv-cli
        run: |
          npm install -g ajv-cli

      - name: Run validation and composing script
        run: pipenv run python builder/run.py -i items -is schemas/single-item.schema.json -o build/item-data.json -eo validation-errors.txt

      - name: Save validation errors as output
        id: save-validation-errors
        if: ${{ failure() }}
        run: |
          echo "validation-errors<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat sample.out)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.save-validation-errors.outputs.validation-errors }}'
            })

      - name: Upload script output as build artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact
        if: ${{ success() }}
        with:
          name: item-data
          path: build/item-data.json
          if-no-files-found: error

  post-validation-errors-comment:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ failure() }}

    steps:
